win_servers:
  hosts:
    nuc12:
      ansible_host: nuc12.hound-banded.ts.net
  vars:
    ansible_user: Administrator
    ansible_connection: ssh
    ansible_shell_type: powershell

    # workaround for error of "Failed to connect to the host via scp: scp: Connection closed"
    # apprently sftp is somehow not working on Windows Server
    # -O flag falls back to the legacy SCP protocol
    ansible_scp_extra_args: "-O"

linux_servers:
  hosts:
    lab-vm-774e5d:
      ansible_host: lab-vm-774e5d.hound-banded.ts.net
  vars:
    ansible_user: ubuntu
    ansible_become: true

k3s_cluster:
  children:
    server:
      hosts:
        lab-vm-774e5d:
