collections:
  - name: https://github.com/k3s-io/k3s-ansible.git
    type: git
    version: 1067f630f5516f7d052057dce549133b90c105f1

  - name: kubernetes.core
    type: galaxy
    version: "==5.3.0"
    source: https://galaxy.ansible.com

roles:
  - name: git+https://github.com/geerlingguy/ansible-role-helm.git
    version: 05a042504840060b91fa97ee5b8429862551254b
